FROM scratch

ENV REPO=/_tmp

FROM docker.io/debian:sid as builder
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update -y -qq && apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 bc build-essential flex bison wget libelf-dev
RUN export KERNEL='6.3.7' && cd /tmp && wget --quiet --no-check-certificate https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL.tar.xz && tar -xf linux-$KERNEL.tar.xz
COPY . $REPO/
RUN $REPO/test/container/kernel-tiny.sh

FROM docker.io/alpine:edge as builder2
COPY . $REPO/
RUN $REPO/test/container/rootfs-tiny.sh

FROM scratch
COPY --from=builder2 / /
COPY --from=builder /boot /boot
COPY --from=builder /lib/modules /lib/modules
