name: Manual test

on:
    workflow_dispatch:
        inputs:
            test:
                description: "Array of tests to run, such as [11,12]"
                default: "['04']"
            container:
                type: choice
                description: 'distro'
                default: 'fedora'
                options:
                    - "fedora"
                    - "arch"
                    - "debian"
                    - "opensuse"
                    - "gentoo"

jobs:
    matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0
            -   id: set-matrix
                name: "Set Matrix"
                run: |
                     [[ "${{ toJson(fromJson(inputs.test)) }}" != '[]' ]] && echo "matrix=${{ inputs.test }}" >> $GITHUB_OUTPUT \
                     || ( tests=$(find test -type d -a -name "TEST-*" | cut -d\- -f2 | sed -z 's/\n/","/g' ); echo "matrix=[\"${tests%??}]" >> $GITHUB_OUTPUT )
    test:
        needs: matrix
        runs-on: ubuntu-latest
        timeout-minutes: 45
        strategy:
            matrix:
                test: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        container:
            image: ghcr.io/dracutdevs/${{ inputs.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0
            -   name: "${{ inputs.container }} ${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
