name: Manual test

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'Test to run'
                default: ['04']
                required: true
            container:
                type: choice
                description: 'distro'
                default: 'fedora'
                options:
                    - "fedora"
                    - "arch"
                    - "debian"
                    - "opensuse"
                    - "gentoo"

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        strategy:
            matrix:
                test: ${{ fromJSON(github.event.inputs.container) }}
        container:
            image: ghcr.io/dracutdevs/${{ input.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v1
                with:
                    fetch-depth: 0
            -   name: "${{ input.container }} ${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
