name: Manual test

on:
    workflow_dispatch:
        inputs:
            test:
                description: "Array of tests to run, such as [11,12]"
                default: "['04']"
                required: true
            env:
                description: "Enviroment (optional)"
            container:
                type: choice
                description: 'distro'
                default: 'fedora'
                options:
                    - "fedora"
                    - "arch"
                    - "debian"
                    - "opensuse"
                    - "gentoo"
                    - "alpine"

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        env: ${{ fromJSON(inputs.env) }}
        strategy:
            matrix:
                test: ${{ fromJSON(inputs.test) }}
        container:
            image: ghcr.io/laszlogombos/${{ inputs.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: "${{ inputs.container }} ${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
